language: python
sudo: false
matrix:
  include:
  - name: Python 3.4 on Linux
    os: linux
    python: 3.4
  - name: Python 3.5 on Linux
    os: linux
    python: 3.5
  - name: Python 3.7 on Linux
    os: linux
    python: 3.6
  - name: Python 3.7 on Xenial
    dist: xenial
    python: 3.7
  - name: Python 3.7 on MacOS
    os: osx
    osx_image: xcode10.2
    language: generic
install:
  - pip3 install --upgrade pip
  - pip3 install npm
  - pip3 install twine
branches:
  only:
  - master
  - "v/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
cache:
  pip: true
git:
  depth: 5
script: make dist
notifications:
  email:
    on_success: never
deploy:
  - provider: pypi
    user: comwes
    password: $PYPIPROD
    skip_existing: true
    on:
      tags: true
      branch: master
      condition: $TRAVIS_OS_NAME = 'linux'
