language: python
sudo: false
env: PYTHON=python
matrix:
  include:
  - name: Python 3.4 on Linux
    os: linux
    python: 3.4
  - name: Python 3.5 on Linux
    os: linux
    python: 3.5
  - name: Python 3.7 on Linux
    os: linux
    python: 3.6
  - name: Python 3.7 on Xenial
    dist: xenial
    python: 3.7
  - name: Python 3.7 on MacOS
    os: osx
    osx_image: xcode10.2
    language: generic
install:
- pip3 install --upgrade pip
- pip install npm
branches:
  only:
  - master
  - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
cache:
  pip: true
git:
  depth: 5
script: make dist
notifications:
  email:
    on_success: never
deploy:
  provider: pypi
  user: comwes
  password:
    secure: p7/b8fYpk15+6WUF3zeHFp838dHO/xTx1vNBEv2fcLVvSdqLyTWsBHqSIsUsyrEujOqa7t95ZP68+dgdOBQB+4cCsITfuIOio6jQHzrn7nMl+CYEfIOHyzFXKqR3ySJo0phRJuwu1hjzdWs4jrWPV2PvhacCbvWhIt4Jw/oZcMWsg0tAxvHRoxMYVi8GdcihOmuSPBSyEUnA6/TBTb8LvxsitE8scfylz0ECCajiE3Cel5UyxorbeTfm8Vk6RHlyJDxPh8GpPRry496Pwp/sM6rk5IX0jLJA0dTFaV7fMYVadRkYjs4U9E9L8Hcka4WGOJ2MgdnFqjnD7Pjup11FSi54fMimDLXa6wmLg54oP20Sd2p9zH/5wq/r9mOfUzcCXvHExFt4LYr83lhUKyZsuSVsb1T/m0+6SXq/CEirDJrO2STkMUyUTL2orksCox5nUvk+XUBcTQE/GU09nlNRn2n6R5GH+CUACVKSnRJaOmMhTMZLi4Bfj5tSD6uGw7sxTPO0+70gEU2J2X8HD315cufMMRR7hpzcQtZ0Vwdegy7jE6cB6lQcruPn+ggGwWZfODeXXKuIWLR7RTN+bxUTnU+HrvugLZEdFZiTpdoLD2sCVunoPrzNST+YG6UjTF+ocMbtKJV6S94UYyUMFAdDxbBMfnRVqD20TLVRxEN6gVc=
  on:
    tags: true
    branch: master
